/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telegrambotadmin;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;  // <-- Tambahkan ini
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;     // <-- Tambahkan ini
import javax.swing.table.DefaultTableModel;
import telegrambotadmin.KelolaKataKunci;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;





        


/**
 *
 * @author espej
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        
        initComponents();
        loadDataMember();
        loadPesanKeluarMasuk();
        setLocationRelativeTo(null); 
        
        Timer timer = new Timer(2000, new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            loadPesanKeluarMasuk();
        }
    });
    timer.start();
    }
    public void clearInput() {
        txtNomorHP.setText("");
        txtUsername.setText("");
        txtChatId.setText("");
    }
    public void loadPesanKeluarMasuk() {
    try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = """
            SELECT h.pesan, h.sumber, m.username 
            FROM history h 
            LEFT JOIN member m ON h.chat_id = m.chat_id 
            ORDER BY h.waktu ASC
            """;
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        StringBuilder chatLog = new StringBuilder();
        while (rs.next()) {
            String sumber = rs.getString("sumber");
            String username = rs.getString("username");
            String pesan = rs.getString("pesan");

            if (username == null) username = "(unknown)";
            if ("user".equalsIgnoreCase(sumber)) {
    chatLog.append(username).append(" : ").append(pesan).append("\n");
} else if ("bot".equalsIgnoreCase(sumber)) {
    chatLog.append("BOT : ").append(pesan).append("\n");
} else {
    chatLog.append(username).append(" : ").append(pesan).append("\n");
}
        }
        txtpesan.setText(chatLog.toString());
        rs.close(); pst.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    
    private String selectedChatId = "";


    public void loadDataMember() {
    DefaultTableModel model = (DefaultTableModel) tabelMember.getModel();
    model.setRowCount(0); // bersihkan tabel dulu

    try {
        Connection conn = DatabaseConnection.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM member");
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nomor_hp"),
                rs.getString("username"),
                rs.getString("chat_id")
            });
        }
        rs.close();
        st.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomorHP = new javax.swing.JTextField();
        txtChatId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btndaftar = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnbroadcast = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpesan = new javax.swing.JTextArea();
        btnkatakunci = new javax.swing.JToggleButton();
        btndatabase = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        btnrefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("KELOLA MEMBER");

        jLabel2.setText("No Handphone");

        jLabel3.setText("Username");

        jLabel4.setText("Char Id");

        txtNomorHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomorHPActionPerformed(evt);
            }
        });

        txtChatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChatIdActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btndaftar.setBackground(new java.awt.Color(102, 255, 102));
        btndaftar.setText("DAFTAR");
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(255, 255, 102));
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 102, 102));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("DATA  MEMBER");

        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No Handphone", "Username", "Chat ID"
            }
        ));
        tabelMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMember);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("BROADCAST PESAN");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnbroadcast.setBackground(new java.awt.Color(102, 255, 102));
        btnbroadcast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbroadcast.setText("BROADCAST");
        btnbroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbroadcastActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("PESAN KELUAR DAN MASUK");

        txtpesan.setColumns(20);
        txtpesan.setRows(5);
        jScrollPane3.setViewportView(txtpesan);

        btnkatakunci.setBackground(new java.awt.Color(102, 255, 255));
        btnkatakunci.setText("KELOKA KATA KUNCI");
        btnkatakunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkatakunciActionPerformed(evt);
            }
        });

        btndatabase.setBackground(new java.awt.Color(102, 153, 255));
        btndatabase.setText("DATABASE PESAN");
        btndatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatabaseActionPerformed(evt);
            }
        });

        jToggleButton4.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton4.setText("KELUAR");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        btnrefresh.setBackground(new java.awt.Color(51, 255, 204));
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbroadcast, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnkatakunci)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btndatabase)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton4))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChatId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndaftar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnedit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnhapus))
                            .addComponent(jLabel6))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(btnrefresh))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomorHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtChatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndaftar)
                            .addComponent(btnedit)
                            .addComponent(btnhapus))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnrefresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbroadcast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkatakunci)
                    .addComponent(btndatabase)
                    .addComponent(jToggleButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtNomorHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorHPActionPerformed

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
        // TODO add your handling code here:
    if (txtNomorHP.getText().isEmpty() || txtUsername.getText().isEmpty() || txtChatId.getText().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
    }
    try {
    Connection conn = DatabaseConnection.getConnection();
    String sql = "INSERT INTO member (nomor_hp, username, chat_id) VALUES (?, ?, ?)";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, txtNomorHP.getText());
    pst.setString(2, txtUsername.getText());
    pst.setString(3, txtChatId.getText());
    pst.executeUpdate();
    JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
    loadDataMember();
    clearInput();
    pst.close();
} catch (SQLException e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_btndaftarActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
      if (txtNomorHP.getText().isEmpty() || txtUsername.getText().isEmpty() || txtChatId.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data dari tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "UPDATE member SET nomor_hp=?, username=? WHERE chat_id=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtNomorHP.getText());
        pst.setString(2, txtUsername.getText());
        pst.setString(3, txtChatId.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
        pst.close();
        loadDataMember();
        clearInput();
    } catch (SQLException e) {
        e.printStackTrace();
    }

    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
     
 if (txtChatId.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            Connection conn = DatabaseConnection.getConnection();
            String sql = "DELETE FROM member WHERE chat_id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtChatId.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            pst.close();
            loadDataMember();
            clearInput();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    }//GEN-LAST:event_btnhapusActionPerformed

    private void tabelMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMemberMouseClicked
        // TODO add your handling code here:
        txtChatId.setEditable(false);
         int row = tabelMember.getSelectedRow();
    if (row != -1) {
        selectedChatId = tabelMember.getValueAt(row, 2).toString();
    }
    int selectedRow = tabelMember.getSelectedRow();

    if (selectedRow >= 0) {
        String nomorHp = tabelMember.getValueAt(selectedRow, 0).toString();
        String username = tabelMember.getValueAt(selectedRow, 1).toString();
        String chatId = tabelMember.getValueAt(selectedRow, 2).toString();

        txtNomorHP.setText(nomorHp);
        txtUsername.setText(username);
        txtChatId.setText(chatId);
    }

    }//GEN-LAST:event_tabelMemberMouseClicked

    private void btnbroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbroadcastActionPerformed
        // TODO add your handling code here:
        String pesanBroadcast = jTextArea1.getText();
    if (pesanBroadcast.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pesan broadcast tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection conn = DatabaseConnection.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT chat_id FROM member");

        // Instance bot
        MyTelegramBot bot = new MyTelegramBot();

        while (rs.next()) {
            String chatId = rs.getString("chat_id");
            bot.kirimPesan(chatId, pesanBroadcast);
        }

        JOptionPane.showMessageDialog(this, "Broadcast berhasil dikirim ke semua member!");
        jTextArea1.setText("");
        rs.close();
        st.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnbroadcastActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void btnkatakunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkatakunciActionPerformed
        // TODO add your handling code here:
    KelolaKataKunci kataKunciForm = new KelolaKataKunci();
    kataKunciForm.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnkatakunciActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
         loadDataMember();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btndatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatabaseActionPerformed
        // TODO add your handling code here:
        DatabasePesan d = new DatabasePesan();
    d.setVisible(true);
    dispose();
    }//GEN-LAST:event_btndatabaseActionPerformed

    private void txtChatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChatIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtChatIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnbroadcast;
    private javax.swing.JButton btndaftar;
    private javax.swing.JToggleButton btndatabase;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JToggleButton btnkatakunci;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JTable tabelMember;
    private javax.swing.JTextField txtChatId;
    private javax.swing.JTextField txtNomorHP;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea txtpesan;
    // End of variables declaration//GEN-END:variables
}
